services:

  auth-service:
    container_name: auth-service

    build: 
      context: ./auth
      dockerfile: Dockerfile

    environment:
      - DB_URL=jdbc:mariadb://auth-db:3306/auth
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      auth-db: 
        condition: service_healthy

  auth-db:
    image: mariadb
    container_name: auth-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth  
    ports:
      - "33062:3306"
    volumes:
      - auth_db_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

volumes:
  auth_db_data: